#!/usr/bin/env python3
"""Generate ptrace + optional memcage arch backend from JSON spec."""

import json
import sys
from pathlib import Path
from typing import List

TEMPLATE = r'''/*
 * AUTO-GENERATED FILE.
 * Generated by tools/generate_arch_backend.py from {spec_path}
 * Manual sections are explicitly marked with MANUAL_TODO.
 */

#define _GNU_SOURCE
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>
#ifdef __linux__
#include <sys/ptrace.h>
#include <sys/user.h>
#endif

#include "../include/injector.h"
#include "../include/arch.h"

#ifdef USE_CAPSTONE
#include <capstone/capstone.h>
static csh cs_handle;
static cs_insn* cs_insn_ptr;
#endif

extern config_t config;
extern state_t state;
extern uint32_t cs_mode_override;

static const blacklist_entry_t blacklist[] = {{
{blacklist_entries}
    {{ 0, 0, NULL }},
}};

/* memcage state (generated scaffold) */
{memcage_state_decl}

static bool insn_blacklisted(insn_t insn)
{{
    for (int i = 0; blacklist[i].reason != NULL; i++) {{
        if ((insn & blacklist[i].mask) == blacklist[i].pattern) {{
            return true;
        }}
    }}
    return false;
}}

void arch_check_cli_config(void)
{{
{arch_check_body}
}}

void arch_init_memory(void)
{{
{arch_init_memory_body}
}}

void arch_cleanup_memory(void)
{{
{arch_cleanup_memory_body}
}}

void fault_handler(int signo, siginfo_t* info, void* context)
{{
{fault_handler_body}
}}

void arch_init_signal_handlers(void)
{{
{arch_init_signal_handlers_body}
}}

void arch_init_disassembler(void)
{{
#ifdef USE_CAPSTONE
    cs_mode mode = cs_mode_override ? (cs_mode)cs_mode_override : ({capstone_mode});
    if (cs_open({capstone_arch}, mode, &cs_handle) != CS_ERR_OK) {{
        fprintf(stderr, "Failed to initialize Capstone for {arch}\\n");
        exit(1);
    }}
    cs_insn_ptr = cs_malloc(cs_handle);
#endif
}}

void arch_cleanup_disassembler(void)
{{
#ifdef USE_CAPSTONE
    if (cs_insn_ptr)
        cs_free(cs_insn_ptr, 1);
    cs_close(&cs_handle);
#endif
}}

bool arch_disassemble_instruction(insn_info_t* insn, disas_t* result)
{{
    result->known = 0;
    result->illegal = 0;
    result->length = 0;
    result->mnemonic[0] = '\0';
    result->operands[0] = '\0';
#ifdef USE_CAPSTONE
    uint8_t buf[4];
    memcpy(buf, &insn->encoding, 4);
    const uint8_t* code = buf;
    size_t code_size = 4;
    uint64_t address = 0;
    if (cs_disasm_iter(cs_handle, &code, &code_size, &address, cs_insn_ptr)) {{
        result->known = 1;
        result->illegal = cs_insn_ptr->illegal ? 1 : 0;
        result->length = (int)address;
        strncpy(result->mnemonic, cs_insn_ptr->mnemonic, sizeof(result->mnemonic) - 1);
        strncpy(result->operands, cs_insn_ptr->op_str, sizeof(result->operands) - 1);
        return true;
    }}
#endif
    return false;
}}

void arch_inject_instruction(insn_info_t* insn)
{{
{arch_inject_body}
}}

bool arch_move_next_instruction(void)
{{
    insn_t next;
    if (config.range.start > config.range.end)
        return false;

    if (!config.range.started) {{
        config.range.started = true;
        next = config.range.start;
        while (next <= config.range.end && insn_blacklisted(next)) {{
            if (next == UINT32_MAX)
                return false;
            next++;
        }}
        if (next > config.range.end)
            return false;
        state.current.encoding = next;
        state.current.size = {insn_size};
        return true;
    }}

    if (config.mode == MODE_RANDOM) {{
        next = (insn_t)rand();
        while (insn_blacklisted(next))
            next = (insn_t)rand();
        state.current.encoding = next;
        state.current.size = {insn_size};
        return true;
    }}

    if (state.current.encoding >= config.range.end)
        return false;

    next = state.current.encoding + 1;
    while (next <= config.range.end && insn_blacklisted(next)) {{
        if (next == UINT32_MAX)
            return false;
        next++;
    }}
    if (next > config.range.end)
        return false;
    state.current.encoding = next;
    state.current.size = {insn_size};
    return true;
}}

bool arch_is_hint_instruction(insn_t insn)
{{
    (void)insn;
    return false;
}}

const char* arch_identify_known_extension(insn_t insn)
{{
    (void)insn;
    return NULL;
}}

bool arch_is_blacklisted(insn_t insn)
{{
    return insn_blacklisted(insn);
}}

int arch_get_instruction_size(insn_t insn)
{{
    (void)insn;
    return {insn_size};
}}

#ifdef __linux__
{reg_struct_decl}

static int ptrace_get_regs(pid_t pid, void* regs)
{{
    return ptrace(PTRACE_GETREGS, pid, NULL, regs) < 0 ? -1 : 0;
}}

static int ptrace_set_regs(pid_t pid, const void* regs)
{{
    return ptrace(PTRACE_SETREGS, pid, NULL, (void*)regs) < 0 ? -1 : 0;
}}

static void ptrace_seed_regs(void* regs, uintptr_t test_pc, uint64_t safe_val)
{{
    {reg_struct}* r = ({reg_struct}*)regs;
    for (int i = 0; i < {gpr_count}; i++)
        r->{gpr_field}[i] = safe_val;
    r->{pc_field} = (uint64_t)test_pc;
}}

static uintptr_t ptrace_get_pc(const void* regs)
{{
    return (uintptr_t)((const {reg_struct}*)regs)->{pc_field};
}}

static void ptrace_classify_stop(int wstatus,
                                 uintptr_t test_addr,
                                 int insn_size,
                                 const void* regs_before,
                                 const void* regs_after,
                                 uint32_t* signum,
                                 uint32_t* sicode)
{{
    (void)regs_before;
    const {reg_struct}* after = (const {reg_struct}*)regs_after;
    *signum = 0;
    *sicode = 0;

    if (!WIFSTOPPED(wstatus))
        return;

    int sig = WSTOPSIG(wstatus);
    if (sig == SIGTRAP) {{
        if ((uintptr_t)after->{pc_field} == test_addr + (uintptr_t)insn_size)
            *signum = 0;
        else if ((uintptr_t)after->{pc_field} == test_addr) {{
            *signum = SIGILL;
            *sicode = 1;
        }}
    }} else if (sig == SIGILL) {{
        if ((uintptr_t)after->{pc_field} == test_addr) {{
            *signum = SIGILL;
            *sicode = 1;
        }}
    }} else {{
        *signum = (uint32_t)sig;
        *sicode = 1;
    }}
}}

static void ptrace_report_reg_diff(const void* regs_before,
                                   const void* regs_after,
                                   insn_t encoding)
{{
    const {reg_struct}* before = (const {reg_struct}*)regs_before;
    const {reg_struct}* after = (const {reg_struct}*)regs_after;
    bool any = false;
    for (int i = 0; i < {gpr_count}; i++) {{
        if (before->{gpr_field}[i] != after->{gpr_field}[i]) {{
            if (!any) {{
                fprintf(stderr, "  regdiff 0x%08x:", encoding);
                any = true;
            }}
            fprintf(stderr, " r%d=0x%lx->0x%lx",
                    i,
                    (unsigned long)before->{gpr_field}[i],
                    (unsigned long)after->{gpr_field}[i]);
        }}
    }}
    if (before->{pc_field} + {insn_size} != after->{pc_field}) {{
        if (!any) {{
            fprintf(stderr, "  regdiff 0x%08x:", encoding);
            any = true;
        }}
        fprintf(stderr, " pc=0x%lx->0x%lx",
                (unsigned long)before->{pc_field},
                (unsigned long)after->{pc_field});
    }}
    if (any)
        fprintf(stderr, "\\n");
}}

static const arch_ptrace_ops_t generated_ptrace_ops = {{
    .name = "{arch}",
    .sentinel_insn = {sentinel},
    .regs_size = sizeof({reg_struct}),
    .get_regs = ptrace_get_regs,
    .set_regs = ptrace_set_regs,
    .seed_regs = ptrace_seed_regs,
    .get_pc = ptrace_get_pc,
    .classify_stop = ptrace_classify_stop,
    .report_reg_diff = ptrace_report_reg_diff,
}};
#else
static const arch_ptrace_ops_t generated_ptrace_ops = {{ 0 }};
#endif

const arch_ptrace_ops_t* arch_get_ptrace_ops(void)
{{
    return &generated_ptrace_ops;
}}
'''

TODO_TEMPLATE = """# Memcage Manual TODOs for {arch}

This checklist is generated from `{spec_path}`.

## Why manual work is still needed

The generated backend provides a compilable memcage baseline, but high-quality memcage
usually needs ISA-specific tuning that cannot be inferred safely from config.

## Required manual checks

{manual_checks}
"""


def build_blacklist(entries):
    lines = []
    for e in entries:
        lines.append(f'    {{ {e["pattern"]}, {e["mask"]}, "{e["reason"]}" }},')
    return "\n".join(lines)


def indent(code: str, level: int = 1) -> str:
    prefix = "    " * level
    return "\n".join((prefix + line) if line else "" for line in code.splitlines())


def memcage_sections(spec):
    mem = spec.get("memcage", {})
    enabled = bool(mem.get("enabled", False))
    sentinel = spec["sentinel_insn"]
    insn_size = int(spec["fixed_insn_size"])
    success_signal = mem.get("success_signal", "SIGTRAP")

    if not enabled:
        return {
            "state_decl": "/* memcage disabled by spec */",
            "check_body": (
                'if (config.exec_method != EXEC_PTRACE) {\n'
                f'    fprintf(stderr, "injector ({spec["arch"]}): only --ptrace is currently supported\\\\n");\n'
                "    exit(1);\n"
                "}\n"
                "if (config.filter_known_ext || config.strict_filter) {\n"
                f'    fprintf(stderr, "injector ({spec["arch"]}): --filter-ext / --strict-filter are ignored\\\\n");\n'
                "}"
            ),
            "init_memory": "(void)0;",
            "cleanup_memory": "(void)0;",
            "fault_handler": "(void)signo; (void)info; (void)context;",
            "init_signal_handlers": "(void)0;",
            "inject_body": (
                "(void)insn;\n"
                f'fprintf(stderr, "injector ({spec["arch"]}): cage path is unsupported; use --ptrace\\\\n");\n'
                "exit(1);"
            ),
            "manual": mem.get("manual_checks", []),
        }

    state_decl = """static void* guard_region = NULL;
static void* packet_bufs[2];
static int active_buf = 0;
static void* packet_buffer = NULL;
static void* trap_page = NULL;
static uint8_t* packet = NULL;
static char alt_stack[ALT_STACK_SIZE];
static stack_t ss;
static sigjmp_buf jmp_env;
static volatile int caught_signal;
static volatile int caught_sicode;
static volatile uintptr_t caught_addr;"""

    check_body = f"""if (config.filter_known_ext || config.strict_filter) {{
    fprintf(stderr, "injector ({spec["arch"]}): --filter-ext / --strict-filter are ignored\\n");
}}"""

    init_memory = f"""size_t total = GUARD_REGION_SIZE;
guard_region = mmap(NULL, total, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
if (guard_region == MAP_FAILED) {{
    perror("mmap guard region failed");
    exit(1);
}}
packet_bufs[0] = (uint8_t*)guard_region + GUARD_PAGES * PAGE_SIZE;
packet_bufs[1] = (uint8_t*)packet_bufs[0] + PAGE_SIZE;
trap_page = (uint8_t*)packet_bufs[1] + PAGE_SIZE;
active_buf = 0;
packet_buffer = packet_bufs[0];

if (config.allow_rwx) {{
    for (int b = 0; b < 2; b++) {{
        if (mprotect(packet_bufs[b], PAGE_SIZE, PROT_READ | PROT_WRITE | PROT_EXEC) != 0) {{
            perror("mprotect test page RWX failed");
            exit(1);
        }}
    }}
}}

for (int b = 0; b < 2; b++) {{
    for (int i = 0; i < PAGE_SIZE / 4; i++) {{
        ((uint32_t*)packet_bufs[b])[i] = {sentinel};
    }}
}}

if (mprotect(trap_page, PAGE_SIZE, PROT_READ | PROT_WRITE) != 0) {{
    perror("mprotect trap page RW failed");
    exit(1);
}}
for (int i = 0; i < PAGE_SIZE / 4; i++) {{
    ((uint32_t*)trap_page)[i] = {sentinel};
}}
if (mprotect(trap_page, PAGE_SIZE, PROT_READ | PROT_EXEC) != 0) {{
    perror("mprotect trap page RX failed");
    exit(1);
}}"""

    cleanup_memory = """if (guard_region) {
    munmap(guard_region, GUARD_REGION_SIZE);
    guard_region = NULL;
}"""

    fault_handler = """(void)context;
caught_signal = signo;
caught_sicode = info ? info->si_code : 0;
caught_addr = info ? (uintptr_t)info->si_addr : 0;
siglongjmp(jmp_env, 1);"""

    init_signal_handlers = """struct sigaction sa;
ss.ss_sp = alt_stack;
ss.ss_size = ALT_STACK_SIZE;
ss.ss_flags = 0;
sigaltstack(&ss, NULL);

sa.sa_sigaction = fault_handler;
sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
sigfillset(&sa.sa_mask);

sigaction(SIGILL, &sa, NULL);
sigaction(SIGSEGV, &sa, NULL);
sigaction(SIGFPE, &sa, NULL);
sigaction(SIGBUS, &sa, NULL);
sigaction(SIGTRAP, &sa, NULL);
sigaction(SIGABRT, &sa, NULL);
sigaction(SIGALRM, &sa, NULL);"""

    sandbox = mem.get("register_sandbox", "none")
    if sandbox == "mips_basic":
        exec_block = """#ifdef __mips__
register uintptr_t safe_reg __asm__("$8") = (uintptr_t)trap_page + PAGE_SIZE / 2;
register uintptr_t target_reg __asm__("$9") = (uintptr_t)packet;
__asm__ volatile(
    "move $2, $8\\n"
    "move $3, $8\\n"
    "move $4, $8\\n"
    "move $5, $8\\n"
    "move $6, $8\\n"
    "move $7, $8\\n"
    "move $10, $8\\n"
    "move $11, $8\\n"
    "move $12, $8\\n"
    "move $13, $8\\n"
    "move $14, $8\\n"
    "move $15, $8\\n"
    "move $16, $8\\n"
    "move $17, $8\\n"
    "move $18, $8\\n"
    "move $19, $8\\n"
    "move $20, $8\\n"
    "move $21, $8\\n"
    "move $22, $8\\n"
    "move $23, $8\\n"
    "move $24, $8\\n"
    "move $25, $8\\n"
    "move $31, $8\\n"
    "jr $9\\n"
    "nop\\n"
    :
    : "r"(safe_reg), "r"(target_reg)
    : "memory", "$2", "$3", "$4", "$5", "$6", "$7",
      "$10", "$11", "$12", "$13", "$14", "$15",
      "$16", "$17", "$18", "$19", "$20", "$21", "$22", "$23",
      "$24", "$25", "$31");
#else
void (*exec)(void) = (void (*)(void))packet;
exec();
#endif"""
    else:
        exec_block = mem.get(
            "exec_block",
            "void (*exec)(void) = (void (*)(void))packet;\nexec();",
        )
    inject_body = f"""if (!config.allow_rwx) {{
    packet_buffer = packet_bufs[active_buf];
}}
packet = (uint8_t*)packet_buffer;

for (int i = 0; i < PAGE_SIZE / 4; i++) {{
    ((uint32_t*)packet)[i] = {sentinel};
}}
memcpy(packet, &insn->encoding, {insn_size});
memcpy(packet + {insn_size}, &(uint32_t){{{sentinel}}}, 4);

if (!config.allow_rwx) {{
    mprotect(packet_buffer, PAGE_SIZE, PROT_READ | PROT_EXEC);
}}
__builtin___clear_cache((char*)packet, (char*)packet + {insn_size} + 4);

memset(&state.result, 0, sizeof(state.result));
caught_signal = 0;
caught_sicode = 0;
caught_addr = 0;
alarm(1);

if (sigsetjmp(jmp_env, 1) == 0) {{
{indent(exec_block, 1)}
}}

alarm(0);
state.result.valid = 1;
state.result.insn_size = {insn_size};

uintptr_t test_addr = (uintptr_t)packet;
uintptr_t sentinel_addr = test_addr + {insn_size};
if (caught_signal == SIGALRM) {{
    state.result.signum = SIGALRM;
    state.result.si_code = caught_sicode;
}} else if (caught_signal == {success_signal}) {{
    if (caught_addr == test_addr) {{
        state.result.signum = SIGILL;
        state.result.si_code = caught_sicode;
    }} else {{
        state.result.signum = 0;
        state.result.si_code = 0;
    }}
}} else if (caught_signal == SIGILL) {{
    if (caught_addr == test_addr) {{
        state.result.signum = SIGILL;
        state.result.si_code = caught_sicode;
    }} else if (caught_addr == sentinel_addr) {{
        state.result.signum = 0;
        state.result.si_code = 0;
    }} else {{
        state.result.signum = 0;
        state.result.si_code = 0;
    }}
}} else {{
    state.result.signum = caught_signal;
    state.result.si_code = caught_sicode;
}}

if (!config.allow_rwx) {{
    mprotect(packet_buffer, PAGE_SIZE, PROT_READ | PROT_WRITE);
    active_buf ^= 1;
}}

/*
 * MANUAL_TODO({spec["arch"]}):
 * Current generated memcage may still need ISA-specific hardening:
 * signal semantics validation, additional blacklists, and optional trampoline.
 */"""

    return {
        "state_decl": state_decl,
        "check_body": check_body,
        "init_memory": init_memory,
        "cleanup_memory": cleanup_memory,
        "fault_handler": fault_handler,
        "init_signal_handlers": init_signal_handlers,
        "inject_body": inject_body,
        "manual": mem.get("manual_checks", []),
    }


def generate(spec_path: Path, out_path: Path) -> None:
    spec = json.loads(spec_path.read_text())
    required = [
        "arch",
        "capstone_arch_macro",
        "capstone_mode_macro",
        "sentinel_insn",
        "pc_field",
        "gpr_field",
        "gpr_count",
        "reg_struct",
        "fixed_insn_size",
    ]
    missing = [k for k in required if k not in spec]
    if missing:
        raise SystemExit(f"Missing required keys in {spec_path}: {', '.join(missing)}")

    reg_struct_decl = spec.get(
        "ptrace_reg_struct_decl",
        "struct mips_ptrace_regs {\n"
        "    uint64_t regs[32];\n"
        "    uint64_t lo;\n"
        "    uint64_t hi;\n"
        "    uint64_t cp0_epc;\n"
        "    uint64_t cp0_badvaddr;\n"
        "    uint64_t cp0_status;\n"
        "    uint64_t cp0_cause;\n"
        "};",
    )
    mem = memcage_sections(spec)
    content = TEMPLATE.format(
        spec_path=spec_path.as_posix(),
        arch=spec["arch"],
        capstone_arch=spec["capstone_arch_macro"],
        capstone_mode=spec["capstone_mode_macro"],
        sentinel=spec["sentinel_insn"],
        reg_struct=spec["reg_struct"],
        reg_struct_decl=reg_struct_decl,
        pc_field=spec["pc_field"],
        gpr_field=spec["gpr_field"],
        gpr_count=int(spec["gpr_count"]),
        insn_size=int(spec["fixed_insn_size"]),
        blacklist_entries=build_blacklist(spec.get("blacklist", [])),
        memcage_state_decl=mem["state_decl"],
        arch_check_body=mem["check_body"],
        arch_init_memory_body=mem["init_memory"],
        arch_cleanup_memory_body=mem["cleanup_memory"],
        fault_handler_body=mem["fault_handler"],
        arch_init_signal_handlers_body=mem["init_signal_handlers"],
        arch_inject_body=mem["inject_body"],
    )
    out_path.write_text(content)

    todo_path = out_path.with_suffix(out_path.suffix + ".MEMCAGE_TODO.md")
    manual_checks = mem["manual"] or [
        "Add ISA-specific register sandbox for memcage safety/perf.",
        "Decide whether trampoline assembly is required for special registers.",
        "Validate signal classification on native hardware.",
    ]
    todo_path.write_text(
        TODO_TEMPLATE.format(
            arch=spec["arch"],
            spec_path=spec_path.as_posix(),
            manual_checks="\n".join(f"- [ ] {item}" for item in manual_checks),
        )
    )


def main(argv: List[str]) -> int:
    if len(argv) != 3:
        print("Usage: generate_arch_backend.py <spec.json> <output.c>")
        return 1
    spec = Path(argv[1])
    out = Path(argv[2])
    generate(spec, out)
    print(f"Generated {out}")
    print(f"Generated {out}.MEMCAGE_TODO.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
