/*
 * AUTO-GENERATED FILE.
 * Generated by tools/generate_arch_backend.py from arch-specs/mips64el.json
 * Manual sections are explicitly marked with MANUAL_TODO.
 */

#define _GNU_SOURCE
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>
#ifdef __linux__
#include <sys/ptrace.h>
#include <sys/user.h>
#endif

#include "../include/injector.h"
#include "../include/arch.h"

#ifdef USE_CAPSTONE
#include <capstone/capstone.h>
static csh cs_handle;
static cs_insn* cs_insn_ptr;
#endif

extern config_t config;
extern state_t state;
extern uint32_t cs_mode_override;

static const blacklist_entry_t blacklist[] = {
    { 0x0000000c, 0xffffffff, "syscall" },
    { 0x0000000d, 0xffffffff, "break" },
    { 0, 0, NULL },
};

/* memcage state (generated scaffold) */
static void* guard_region = NULL;
static void* packet_bufs[2];
static int active_buf = 0;
static void* packet_buffer = NULL;
static void* trap_page = NULL;
static uint8_t* packet = NULL;
static char alt_stack[ALT_STACK_SIZE];
static stack_t ss;
static sigjmp_buf jmp_env;
static volatile int caught_signal;
static volatile int caught_sicode;
static volatile uintptr_t caught_addr;

static bool insn_blacklisted(insn_t insn)
{
    for (int i = 0; blacklist[i].reason != NULL; i++) {
        if ((insn & blacklist[i].mask) == blacklist[i].pattern) {
            return true;
        }
    }
    return false;
}

void arch_check_cli_config(void)
{
if (config.filter_known_ext || config.strict_filter) {
    fprintf(stderr, "injector (mips): --filter-ext / --strict-filter are ignored\n");
}
}

void arch_init_memory(void)
{
size_t total = GUARD_REGION_SIZE;
guard_region = mmap(NULL, total, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
if (guard_region == MAP_FAILED) {
    perror("mmap guard region failed");
    exit(1);
}
packet_bufs[0] = (uint8_t*)guard_region + GUARD_PAGES * PAGE_SIZE;
packet_bufs[1] = (uint8_t*)packet_bufs[0] + PAGE_SIZE;
trap_page = (uint8_t*)packet_bufs[1] + PAGE_SIZE;
active_buf = 0;
packet_buffer = packet_bufs[0];

if (config.allow_rwx) {
    for (int b = 0; b < 2; b++) {
        if (mprotect(packet_bufs[b], PAGE_SIZE, PROT_READ | PROT_WRITE | PROT_EXEC) != 0) {
            perror("mprotect test page RWX failed");
            exit(1);
        }
    }
}

for (int b = 0; b < 2; b++) {
    for (int i = 0; i < PAGE_SIZE / 4; i++) {
        ((uint32_t*)packet_bufs[b])[i] = 0x0000000du;
    }
}

if (mprotect(trap_page, PAGE_SIZE, PROT_READ | PROT_WRITE) != 0) {
    perror("mprotect trap page RW failed");
    exit(1);
}
for (int i = 0; i < PAGE_SIZE / 4; i++) {
    ((uint32_t*)trap_page)[i] = 0x0000000du;
}
if (mprotect(trap_page, PAGE_SIZE, PROT_READ | PROT_EXEC) != 0) {
    perror("mprotect trap page RX failed");
    exit(1);
}
}

void arch_cleanup_memory(void)
{
if (guard_region) {
    munmap(guard_region, GUARD_REGION_SIZE);
    guard_region = NULL;
}
}

void fault_handler(int signo, siginfo_t* info, void* context)
{
(void)context;
caught_signal = signo;
caught_sicode = info ? info->si_code : 0;
caught_addr = info ? (uintptr_t)info->si_addr : 0;
siglongjmp(jmp_env, 1);
}

void arch_init_signal_handlers(void)
{
struct sigaction sa;
ss.ss_sp = alt_stack;
ss.ss_size = ALT_STACK_SIZE;
ss.ss_flags = 0;
sigaltstack(&ss, NULL);

sa.sa_sigaction = fault_handler;
sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
sigfillset(&sa.sa_mask);

sigaction(SIGILL, &sa, NULL);
sigaction(SIGSEGV, &sa, NULL);
sigaction(SIGFPE, &sa, NULL);
sigaction(SIGBUS, &sa, NULL);
sigaction(SIGTRAP, &sa, NULL);
sigaction(SIGABRT, &sa, NULL);
sigaction(SIGALRM, &sa, NULL);
}

void arch_init_disassembler(void)
{
#ifdef USE_CAPSTONE
    cs_mode mode = cs_mode_override ? (cs_mode)cs_mode_override : (CS_MODE_MIPS64 | CS_MODE_LITTLE_ENDIAN);
    if (cs_open(CS_ARCH_MIPS, mode, &cs_handle) != CS_ERR_OK) {
        fprintf(stderr, "Failed to initialize Capstone for mips\\n");
        exit(1);
    }
    cs_insn_ptr = cs_malloc(cs_handle);
#endif
}

void arch_cleanup_disassembler(void)
{
#ifdef USE_CAPSTONE
    if (cs_insn_ptr)
        cs_free(cs_insn_ptr, 1);
    cs_close(&cs_handle);
#endif
}

bool arch_disassemble_instruction(insn_info_t* insn, disas_t* result)
{
    result->known = 0;
    result->illegal = 0;
    result->length = 0;
    result->mnemonic[0] = '\0';
    result->operands[0] = '\0';
#ifdef USE_CAPSTONE
    uint8_t buf[4];
    memcpy(buf, &insn->encoding, 4);
    const uint8_t* code = buf;
    size_t code_size = 4;
    uint64_t address = 0;
    if (cs_disasm_iter(cs_handle, &code, &code_size, &address, cs_insn_ptr)) {
        result->known = 1;
        result->illegal = cs_insn_ptr->illegal ? 1 : 0;
        result->length = (int)address;
        strncpy(result->mnemonic, cs_insn_ptr->mnemonic, sizeof(result->mnemonic) - 1);
        strncpy(result->operands, cs_insn_ptr->op_str, sizeof(result->operands) - 1);
        return true;
    }
#endif
    return false;
}

void arch_inject_instruction(insn_info_t* insn)
{
if (!config.allow_rwx) {
    packet_buffer = packet_bufs[active_buf];
}
packet = (uint8_t*)packet_buffer;

for (int i = 0; i < PAGE_SIZE / 4; i++) {
    ((uint32_t*)packet)[i] = 0x0000000du;
}
memcpy(packet, &insn->encoding, 4);
memcpy(packet + 4, &(uint32_t){0x0000000du}, 4);

if (!config.allow_rwx) {
    mprotect(packet_buffer, PAGE_SIZE, PROT_READ | PROT_EXEC);
}
__builtin___clear_cache((char*)packet, (char*)packet + 4 + 4);

memset(&state.result, 0, sizeof(state.result));
caught_signal = 0;
caught_sicode = 0;
caught_addr = 0;
alarm(1);

if (sigsetjmp(jmp_env, 1) == 0) {
    #ifdef __mips__
    register uintptr_t safe_reg __asm__("$8") = (uintptr_t)trap_page + PAGE_SIZE / 2;
    register uintptr_t target_reg __asm__("$9") = (uintptr_t)packet;
    __asm__ volatile(
        "move $2, $8\n"
        "move $3, $8\n"
        "move $4, $8\n"
        "move $5, $8\n"
        "move $6, $8\n"
        "move $7, $8\n"
        "move $10, $8\n"
        "move $11, $8\n"
        "move $12, $8\n"
        "move $13, $8\n"
        "move $14, $8\n"
        "move $15, $8\n"
        "move $16, $8\n"
        "move $17, $8\n"
        "move $18, $8\n"
        "move $19, $8\n"
        "move $20, $8\n"
        "move $21, $8\n"
        "move $22, $8\n"
        "move $23, $8\n"
        "move $24, $8\n"
        "move $25, $8\n"
        "move $31, $8\n"
        "jr $9\n"
        "nop\n"
        :
        : "r"(safe_reg), "r"(target_reg)
        : "memory", "$2", "$3", "$4", "$5", "$6", "$7",
          "$10", "$11", "$12", "$13", "$14", "$15",
          "$16", "$17", "$18", "$19", "$20", "$21", "$22", "$23",
          "$24", "$25", "$31");
    #else
    void (*exec)(void) = (void (*)(void))packet;
    exec();
    #endif
}

alarm(0);
state.result.valid = 1;
state.result.insn_size = 4;

uintptr_t test_addr = (uintptr_t)packet;
uintptr_t sentinel_addr = test_addr + 4;
if (caught_signal == SIGALRM) {
    state.result.signum = SIGALRM;
    state.result.si_code = caught_sicode;
} else if (caught_signal == SIGTRAP) {
    if (caught_addr == test_addr) {
        state.result.signum = SIGILL;
        state.result.si_code = caught_sicode;
    } else {
        state.result.signum = 0;
        state.result.si_code = 0;
    }
} else if (caught_signal == SIGILL) {
    if (caught_addr == test_addr) {
        state.result.signum = SIGILL;
        state.result.si_code = caught_sicode;
    } else if (caught_addr == sentinel_addr) {
        state.result.signum = 0;
        state.result.si_code = 0;
    } else {
        state.result.signum = 0;
        state.result.si_code = 0;
    }
} else {
    state.result.signum = caught_signal;
    state.result.si_code = caught_sicode;
}

if (!config.allow_rwx) {
    mprotect(packet_buffer, PAGE_SIZE, PROT_READ | PROT_WRITE);
    active_buf ^= 1;
}

/*
 * MANUAL_TODO(mips):
 * Current generated memcage may still need ISA-specific hardening:
 * signal semantics validation, additional blacklists, and optional trampoline.
 */
}

bool arch_move_next_instruction(void)
{
    insn_t next;
    if (config.range.start > config.range.end)
        return false;

    if (!config.range.started) {
        config.range.started = true;
        next = config.range.start;
        while (next <= config.range.end && insn_blacklisted(next)) {
            if (next == UINT32_MAX)
                return false;
            next++;
        }
        if (next > config.range.end)
            return false;
        state.current.encoding = next;
        state.current.size = 4;
        return true;
    }

    if (config.mode == MODE_RANDOM) {
        next = (insn_t)rand();
        while (insn_blacklisted(next))
            next = (insn_t)rand();
        state.current.encoding = next;
        state.current.size = 4;
        return true;
    }

    if (state.current.encoding >= config.range.end)
        return false;

    next = state.current.encoding + 1;
    while (next <= config.range.end && insn_blacklisted(next)) {
        if (next == UINT32_MAX)
            return false;
        next++;
    }
    if (next > config.range.end)
        return false;
    state.current.encoding = next;
    state.current.size = 4;
    return true;
}

bool arch_is_hint_instruction(insn_t insn)
{
    (void)insn;
    return false;
}

const char* arch_identify_known_extension(insn_t insn)
{
    (void)insn;
    return NULL;
}

bool arch_is_blacklisted(insn_t insn)
{
    return insn_blacklisted(insn);
}

int arch_get_instruction_size(insn_t insn)
{
    (void)insn;
    return 4;
}

#ifdef __linux__
struct mips_ptrace_regs {
    uint64_t regs[32];
    uint64_t lo;
    uint64_t hi;
    uint64_t cp0_epc;
    uint64_t cp0_badvaddr;
    uint64_t cp0_status;
    uint64_t cp0_cause;
};

static int ptrace_get_regs(pid_t pid, void* regs)
{
    return ptrace(PTRACE_GETREGS, pid, NULL, regs) < 0 ? -1 : 0;
}

static int ptrace_set_regs(pid_t pid, const void* regs)
{
    return ptrace(PTRACE_SETREGS, pid, NULL, (void*)regs) < 0 ? -1 : 0;
}

static void ptrace_seed_regs(void* regs, uintptr_t test_pc, uint64_t safe_val)
{
    struct mips_ptrace_regs* r = (struct mips_ptrace_regs*)regs;
    for (int i = 0; i < 32; i++)
        r->regs[i] = safe_val;
    r->cp0_epc = (uint64_t)test_pc;
}

static uintptr_t ptrace_get_pc(const void* regs)
{
    return (uintptr_t)((const struct mips_ptrace_regs*)regs)->cp0_epc;
}

static void ptrace_classify_stop(int wstatus,
                                 uintptr_t test_addr,
                                 int insn_size,
                                 const void* regs_before,
                                 const void* regs_after,
                                 uint32_t* signum,
                                 uint32_t* sicode)
{
    (void)regs_before;
    const struct mips_ptrace_regs* after = (const struct mips_ptrace_regs*)regs_after;
    *signum = 0;
    *sicode = 0;

    if (!WIFSTOPPED(wstatus))
        return;

    int sig = WSTOPSIG(wstatus);
    if (sig == SIGTRAP) {
        if ((uintptr_t)after->cp0_epc == test_addr + (uintptr_t)insn_size)
            *signum = 0;
        else if ((uintptr_t)after->cp0_epc == test_addr) {
            *signum = SIGILL;
            *sicode = 1;
        }
    } else if (sig == SIGILL) {
        if ((uintptr_t)after->cp0_epc == test_addr) {
            *signum = SIGILL;
            *sicode = 1;
        }
    } else {
        *signum = (uint32_t)sig;
        *sicode = 1;
    }
}

static void ptrace_report_reg_diff(const void* regs_before,
                                   const void* regs_after,
                                   insn_t encoding)
{
    const struct mips_ptrace_regs* before = (const struct mips_ptrace_regs*)regs_before;
    const struct mips_ptrace_regs* after = (const struct mips_ptrace_regs*)regs_after;
    bool any = false;
    for (int i = 0; i < 32; i++) {
        if (before->regs[i] != after->regs[i]) {
            if (!any) {
                fprintf(stderr, "  regdiff 0x%08x:", encoding);
                any = true;
            }
            fprintf(stderr, " r%d=0x%lx->0x%lx",
                    i,
                    (unsigned long)before->regs[i],
                    (unsigned long)after->regs[i]);
        }
    }
    if (before->cp0_epc + 4 != after->cp0_epc) {
        if (!any) {
            fprintf(stderr, "  regdiff 0x%08x:", encoding);
            any = true;
        }
        fprintf(stderr, " pc=0x%lx->0x%lx",
                (unsigned long)before->cp0_epc,
                (unsigned long)after->cp0_epc);
    }
    if (any)
        fprintf(stderr, "\\n");
}

static const arch_ptrace_ops_t generated_ptrace_ops = {
    .name = "mips",
    .sentinel_insn = 0x0000000du,
    .regs_size = sizeof(struct mips_ptrace_regs),
    .get_regs = ptrace_get_regs,
    .set_regs = ptrace_set_regs,
    .seed_regs = ptrace_seed_regs,
    .get_pc = ptrace_get_pc,
    .classify_stop = ptrace_classify_stop,
    .report_reg_diff = ptrace_report_reg_diff,
};
#else
static const arch_ptrace_ops_t generated_ptrace_ops = { 0 };
#endif

const arch_ptrace_ops_t* arch_get_ptrace_ops(void)
{
    return &generated_ptrace_ops;
}
